
LANGUAGES = ["English", "Spanish", "German", "French"]
KINDS = (
    ["explicit"] * 30
    + ["unique"] * 25
    + ["ambiguous"] * 20
    + ["missing"] * 10
    + ["explicit_with_city"] * 10
    + ["distractor"] * 5
)
DIFFICULTIES = ["simple"] * 30 + ["medium"] * 40 + ["hard"] * 30

REQUESTS = {
    "English": [
        "Can {target} provide {quantity} {unit} of {material} by {date}?",
        "Can {quantity} {unit} of {material} be supplied to {target} by {date}?",
        "Please check whether {target} can deliver {quantity} {unit} of {material} on {date}.",
        "We need {quantity} {unit} of {material} at {target} by {date}. Is that possible?",
        "Is {target} able to cover {quantity} {unit} of {material} for {date}?",
        "Check availability at {target} for {quantity} {unit} of {material}, required {date}.",
        "Could {target} fulfill {quantity} {unit} of {material} before {date}?",
        "The requirement is {quantity} {unit} of {material} for {target} on {date}. Can it be met?",
        "Will {target} have {quantity} {unit} of {material} available by {date}?",
        "Please confirm whether {target} can supply {material}, {quantity} {unit}, by {date}.",
        "For {target}, we still need {quantity} {unit} of {material} on {date}. Can we cover it?",
        "The {date} requirement at {target} is short by {quantity} {unit} of {material}. Please check coverage.",
        "Production at {target} needs another {quantity} {unit} of {material} for {date}. Can supply support it?",
        "There is an open requirement for {material} at {target}: {quantity} {unit} due {date}. Please review it.",
        "Could you verify capacity at {target} for the {date} demand of {quantity} {unit} of {material}?",
        "We are planning the {date} run at {target} and require {quantity} {unit} of {material}. Is it coverable?",
        "The current plan leaves {target} needing {quantity} {unit} of {material} by {date}. Can we fulfill it?",
        "Please assess whether the {quantity} {unit} requirement for {material} at {target} can be met on {date}.",
        "For the delivery scheduled on {date}, {target} requires {quantity} {unit} of {material}. Can we commit?",
        "Can the outstanding {material} demand at {target}, totaling {quantity} {unit}, be covered by {date}?",
        "The later requirement is covered. At {target}, the {date} run is short {quantity} {unit} of {material}. Please check that shortfall.",
        "Ignore the completed replenishment; the open issue is {quantity} {unit} of {material} for {target} on {date}. Can we cover it?",
        "Planning has closed the other demand. What remains for {target} is {material}: {quantity} {unit} needed by {date}.",
        "The previous allocation is settled, but {target} still lacks {quantity} {unit} of {material} for the {date} run. Please verify supply.",
        "For the requirement we are discussing—not the later one—{target} needs {quantity} {unit} of {material} on {date}. Is fulfillment possible?",
        "Operations confirmed the other order. The unresolved shortfall at {target} is {quantity} {unit} of {material}, due {date}.",
        "Set aside the already covered demand; can {target} obtain the remaining {quantity} {unit} of {material} by {date}?",
        "The old request can be ignored. Please check the active {date} requirement at {target} for {quantity} {unit} of {material}.",
        "Although the subsequent run is supplied, the one at {target} on {date} still needs {quantity} {unit} of {material}. Can it be covered?",
        "Only the open requirement matters here: {material}, {quantity} {unit}, for {target} by {date}. Please determine whether it can be fulfilled.",
    ],
    "Spanish": [
        "¿Puede {target} suministrar {quantity} {unit} de {material} para el {date}?",
        "¿Se pueden entregar {quantity} {unit} de {material} a {target} antes del {date}?",
        "Comprueba si {target} puede entregar {quantity} {unit} de {material} el {date}.",
        "Necesitamos {quantity} {unit} de {material} en {target} para el {date}. ¿Es posible?",
        "¿Puede {target} cubrir {quantity} {unit} de {material} para el {date}?",
        "Revisa la disponibilidad en {target} de {quantity} {unit} de {material}, necesarios el {date}.",
        "¿Podría {target} atender {quantity} {unit} de {material} antes del {date}?",
        "El requisito es de {quantity} {unit} de {material} para {target} el {date}. ¿Se puede cumplir?",
        "¿Tendrá {target} disponibles {quantity} {unit} de {material} para el {date}?",
        "Confirma si {target} puede suministrar {material}, {quantity} {unit}, antes del {date}.",
        "Para {target} aún necesitamos {quantity} {unit} de {material} el {date}. ¿Podemos cubrirlo?",
        "Al requisito del {date} en {target} le faltan {quantity} {unit} de {material}. Comprueba la cobertura.",
        "La producción de {target} necesita otras {quantity} {unit} de {material} para el {date}. ¿Puede suministro atenderlo?",
        "Hay una necesidad pendiente de {material} en {target}: {quantity} {unit} para el {date}. Revísala.",
        "¿Puedes verificar la capacidad de {target} para la demanda del {date} de {quantity} {unit} de {material}?",
        "Estamos planificando la operación del {date} en {target} y necesitamos {quantity} {unit} de {material}. ¿Se puede cubrir?",
        "El plan actual deja a {target} con una necesidad de {quantity} {unit} de {material} para el {date}. ¿Podemos atenderla?",
        "Evalúa si el requisito de {quantity} {unit} de {material} en {target} puede cumplirse el {date}.",
        "Para la entrega prevista el {date}, {target} requiere {quantity} {unit} de {material}. ¿Podemos comprometernos?",
        "¿Puede cubrirse para el {date} la demanda pendiente de {material} en {target}, que suma {quantity} {unit}?",
        "El requisito posterior ya está cubierto. En {target}, para el {date} faltan {quantity} {unit} de {material}. Comprueba ese faltante.",
        "Ignora la reposición completada; lo pendiente son {quantity} {unit} de {material} para {target} el {date}. ¿Podemos cubrirlo?",
        "Planificación cerró la otra demanda. Lo que queda para {target} es {material}: {quantity} {unit} necesarias el {date}.",
        "La asignación anterior está resuelta, pero a {target} aún le faltan {quantity} {unit} de {material} para el {date}. Verifica el suministro.",
        "Para el requisito que estamos tratando, no el posterior, {target} necesita {quantity} {unit} de {material} el {date}. ¿Es viable?",
        "Operaciones confirmó el otro pedido. El faltante sin resolver en {target} es de {quantity} {unit} de {material}, con fecha {date}.",
        "Deja aparte la demanda ya cubierta; ¿puede {target} obtener las {quantity} {unit} restantes de {material} para el {date}?",
        "La solicitud antigua puede ignorarse. Comprueba el requisito activo del {date} en {target}: {quantity} {unit} de {material}.",
        "Aunque la operación posterior tiene suministro, la de {target} del {date} aún necesita {quantity} {unit} de {material}. ¿Puede cubrirse?",
        "Solo importa la necesidad abierta: {material}, {quantity} {unit}, para {target} antes del {date}. Determina si puede atenderse.",
    ],
    "German": [
        "Kann {target} bis zum {date} {quantity} {unit} {material} liefern?",
        "Können bis zum {date} {quantity} {unit} {material} an {target} geliefert werden?",
        "Bitte prüfe, ob {target} am {date} {quantity} {unit} {material} bereitstellen kann.",
        "Wir benötigen bis zum {date} {quantity} {unit} {material} in {target}. Ist das möglich?",
        "Kann {target} den Bedarf von {quantity} {unit} {material} zum {date} decken?",
        "Prüfe die Verfügbarkeit von {quantity} {unit} {material} in {target} für den {date}.",
        "Könnte {target} vor dem {date} {quantity} {unit} {material} bereitstellen?",
        "Der Bedarf beträgt {quantity} {unit} {material} für {target} am {date}. Kann er erfüllt werden?",
        "Hat {target} bis zum {date} {quantity} {unit} {material} verfügbar?",
        "Bitte bestätige, ob {target} bis zum {date} {material} in einer Menge von {quantity} {unit} liefern kann.",
        "Für {target} fehlen am {date} noch {quantity} {unit} {material}. Können wir das decken?",
        "Beim Bedarf am {date} in {target} fehlen {quantity} {unit} {material}. Bitte prüfe die Deckung.",
        "Die Produktion in {target} benötigt für den {date} weitere {quantity} {unit} {material}. Kann die Versorgung das leisten?",
        "Für {target} besteht ein offener Bedarf an {material}: {quantity} {unit}, fällig am {date}. Bitte prüfen.",
        "Kannst du die Kapazität von {target} für den Bedarf von {quantity} {unit} {material} am {date} prüfen?",
        "Wir planen den Lauf am {date} in {target} und benötigen {quantity} {unit} {material}. Ist das abdeckbar?",
        "Nach aktuellem Plan braucht {target} bis zum {date} noch {quantity} {unit} {material}. Können wir das erfüllen?",
        "Bitte beurteile, ob der Bedarf von {quantity} {unit} {material} in {target} am {date} erfüllt werden kann.",
        "Für die Lieferung am {date} benötigt {target} {quantity} {unit} {material}. Können wir das zusagen?",
        "Kann der offene Bedarf an {material} in {target} von insgesamt {quantity} {unit} bis zum {date} gedeckt werden?",
        "Der spätere Bedarf ist gedeckt. In {target} fehlen für den Lauf am {date} noch {quantity} {unit} {material}. Bitte prüfe diesen Fehlbestand.",
        "Ignoriere die abgeschlossene Auffüllung; offen sind {quantity} {unit} {material} für {target} am {date}. Können wir das decken?",
        "Die Planung hat den anderen Bedarf geschlossen. Für {target} bleiben {quantity} {unit} {material}, benötigt am {date}.",
        "Die frühere Zuteilung ist erledigt, aber {target} fehlen für den {date} noch {quantity} {unit} {material}. Bitte Versorgung prüfen.",
        "Für den aktuellen Bedarf, nicht den späteren, benötigt {target} am {date} {quantity} {unit} {material}. Ist die Erfüllung möglich?",
        "Der andere Auftrag ist bestätigt. Der offene Fehlbestand in {target} beträgt {quantity} {unit} {material} zum {date}.",
        "Lass den bereits gedeckten Bedarf außer Acht; kann {target} die restlichen {quantity} {unit} {material} bis zum {date} erhalten?",
        "Die alte Anfrage kann ignoriert werden. Prüfe den aktiven Bedarf in {target} am {date}: {quantity} {unit} {material}.",
        "Obwohl der spätere Lauf versorgt ist, benötigt der Lauf in {target} am {date} noch {quantity} {unit} {material}. Ist das abdeckbar?",
        "Nur der offene Bedarf zählt: {material}, {quantity} {unit}, für {target} bis zum {date}. Bitte prüfe die Erfüllbarkeit.",
    ],
    "French": [
        "Est-ce que {target} peut fournir {quantity} {unit} de {material} pour le {date} ?",
        "Peut-on livrer {quantity} {unit} de {material} à {target} avant le {date} ?",
        "Merci de vérifier si {target} peut livrer {quantity} {unit} de {material} le {date}.",
        "Nous avons besoin de {quantity} {unit} de {material} à {target} pour le {date}. Est-ce possible ?",
        "{target} peut-il couvrir {quantity} {unit} de {material} pour le {date} ?",
        "Vérifiez la disponibilité à {target} de {quantity} {unit} de {material}, requises le {date}.",
        "Est-ce que {target} pourrait fournir {quantity} {unit} de {material} avant le {date} ?",
        "Le besoin est de {quantity} {unit} de {material} pour {target} le {date}. Peut-il être satisfait ?",
        "{target} disposera-t-il de {quantity} {unit} de {material} d’ici le {date} ?",
        "Merci de confirmer si {target} peut fournir {material}, {quantity} {unit}, avant le {date}.",
        "Pour {target}, il manque encore {quantity} {unit} de {material} le {date}. Peut-on couvrir ce besoin ?",
        "Il manque {quantity} {unit} de {material} pour le besoin du {date} à {target}. Merci de vérifier la couverture.",
        "La production de {target} nécessite encore {quantity} {unit} de {material} pour le {date}. L’approvisionnement peut-il suivre ?",
        "Un besoin de {material} reste ouvert à {target} : {quantity} {unit} pour le {date}. Merci de l’examiner.",
        "Pouvez-vous vérifier la capacité de {target} pour la demande du {date} de {quantity} {unit} de {material} ?",
        "Nous planifions l’activité du {date} à {target} et avons besoin de {quantity} {unit} de {material}. Est-ce réalisable ?",
        "Le plan actuel laisse à {target} un besoin de {quantity} {unit} de {material} pour le {date}. Peut-on le satisfaire ?",
        "Merci d’évaluer si le besoin de {quantity} {unit} de {material} à {target} peut être couvert le {date}.",
        "Pour la livraison prévue le {date}, {target} nécessite {quantity} {unit} de {material}. Pouvons-nous nous engager ?",
        "La demande restante de {material} à {target}, soit {quantity} {unit}, peut-elle être couverte avant le {date} ?",
        "Le besoin ultérieur est couvert. À {target}, il manque {quantity} {unit} de {material} pour le {date}. Merci de vérifier ce manque.",
        "Ignorez le réapprovisionnement terminé ; le besoin ouvert est de {quantity} {unit} de {material} pour {target} le {date}. Peut-on le couvrir ?",
        "La planification a clôturé l’autre demande. Il reste pour {target} {quantity} {unit} de {material}, nécessaires le {date}.",
        "L’affectation précédente est réglée, mais {target} manque encore de {quantity} {unit} de {material} pour le {date}. Vérifiez l’approvisionnement.",
        "Pour le besoin en cours, et non le suivant, {target} nécessite {quantity} {unit} de {material} le {date}. Est-ce réalisable ?",
        "L’autre commande est confirmée. Le manque non résolu à {target} est de {quantity} {unit} de {material}, exigées le {date}.",
        "Écartez la demande déjà couverte ; {target} peut-il obtenir les {quantity} {unit} restantes de {material} avant le {date} ?",
        "L’ancienne demande peut être ignorée. Vérifiez le besoin actif du {date} à {target} : {quantity} {unit} de {material}.",
        "Même si l’activité suivante est approvisionnée, celle de {target} du {date} nécessite encore {quantity} {unit} de {material}. Peut-on la couvrir ?",
        "Seul le besoin ouvert compte : {material}, {quantity} {unit}, pour {target} avant le {date}. Merci de vérifier sa faisabilité.",
    ],
}

DISTRACTOR_PREFIXES = {
    "English": "The previous shipment used {plant_id}, but this request is different. ",
    "Spanish": "El envío anterior utilizó {plant_id}, pero esta solicitud es diferente. ",
    "German": "Die vorherige Lieferung nutzte {plant_id}, aber diese Anfrage ist eine andere. ",
    "French": "La livraison précédente utilisait {plant_id}, mais cette demande est différente. ",
}
